import menderes1 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/1.jpg'
import menderes2 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/2.jpg'
import menderes3 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/3.jpg'
import menderes4 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/4.jpg'
import menderes5 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/5.jpg'
import menderes6 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/6.jpg'
import menderes7 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/7.jpg'
import menderes8 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/8.jpg'
import menderes9 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/9.jpg'
import menderes10 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/10.jpg'
import menderes11 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/11.jpg'
import menderes12 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/12.jpg'
import menderes13 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/13.jpg'
import menderes14 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/14.jpg'
import menderes15 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/15.jpg'
import menderes16 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/16.jpg'
import menderes17 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/17.jpg'
import menderes18 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/18.jpg'
import menderes19 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/19.jpg'
import menderes20 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/20.jpg'
import menderes21 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/21.jpg'
import menderes22 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/H.D. PRIVATE HOUSE- MENDERES/22.jpg'

import kartal1 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/LUXURY BEDROOM-KARTAL YUVASI BODRUM/1.jpg'
import kartal2 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/LUXURY BEDROOM-KARTAL YUVASI BODRUM/2.jpg'
import kartal3 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/LUXURY BEDROOM-KARTAL YUVASI BODRUM/3.jpg'
import kartal4 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/LUXURY BEDROOM-KARTAL YUVASI BODRUM/4.jpg'

import mesa1 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/MESA BODRUM DEMİRBÜKÜ/1.jpg'
import mesa2 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/MESA BODRUM DEMİRBÜKÜ/2.jpg'
import mesa3 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/MESA BODRUM DEMİRBÜKÜ/3.jpg'
import mesa4 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/MESA BODRUM DEMİRBÜKÜ/4.jpg'
import mesa5 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/MESA BODRUM DEMİRBÜKÜ/5.jpg'
import mesa6 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/MESA BODRUM DEMİRBÜKÜ/6.jpg'
import mesa7 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/MESA BODRUM DEMİRBÜKÜ/7.jpg'
import mesa8 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/MESA BODRUM DEMİRBÜKÜ/8.jpg'
import mesa9 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/MESA BODRUM DEMİRBÜKÜ/9.jpg'
import mesa10 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/MESA BODRUM DEMİRBÜKÜ/10.jpg'
import mesa11 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/MESA BODRUM DEMİRBÜKÜ/11.jpg'
import mesa12 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/MESA BODRUM DEMİRBÜKÜ/12.jpg'

import shlsalon1 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/SALON/1.jpg'
import shlsalon2 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/SALON/2.jpg'
import shlsalon3 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/SALON/3.jpg'
import shlsalon4 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/SALON/4.jpg'
import shlsalon5 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/SALON/5.jpg'
import shlsalon6 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/SALON/6.jpg'
import shlsalon7 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/SALON/7.jpg'
import shlsalon8 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/SALON/8.jpg'
import shlsalon9 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/SALON/9.jpg'
import shlsalon10 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/SALON/10.jpg'
import shlsalon11 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/SALON/11.jpg'
import shlsalon12 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/SALON/12.jpg'
import shlsalon13 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/SALON/13.jpg'
import shlsalon14 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/SALON/14.jpg'
import shlyatak1 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/YATAK ODASI/1.jpg'
import shlyatak2 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/YATAK ODASI/2.jpg'
import shlyatak3 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/YATAK ODASI/3.jpg'
import shlyatak4 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/YATAK ODASI/4.jpg'
import shlyatak5 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/YATAK ODASI/5.jpg'
import shlyatak6 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/YATAK ODASI/6.jpg'
import shlyatak7 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/YATAK ODASI/7.jpg'
import shlyatak8 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/PRIVATE VILLA-SAHİLEVLERİ İZMİR/YATAK ODASI/8.jpg'


import sg1 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/Ş.G. PRIVATE VILLA-ISTANBUL/1.jpg'
import sg2 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/Ş.G. PRIVATE VILLA-ISTANBUL/2.jpg'
import sg3 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/Ş.G. PRIVATE VILLA-ISTANBUL/3.jpg'
import sg4 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/Ş.G. PRIVATE VILLA-ISTANBUL/4.jpg'
import sg5 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/Ş.G. PRIVATE VILLA-ISTANBUL/5.jpg'
import sg6 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/Ş.G. PRIVATE VILLA-ISTANBUL/6.jpg'
import sg7 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/Ş.G. PRIVATE VILLA-ISTANBUL/7.jpg'
import sg8 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/Ş.G. PRIVATE VILLA-ISTANBUL/8.jpg'
import sg9 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/Ş.G. PRIVATE VILLA-ISTANBUL/9.jpg'
import sg10 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/Ş.G. PRIVATE VILLA-ISTANBUL/10.jpg'
import sg11 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/Ş.G. PRIVATE VILLA-ISTANBUL/11.jpg'
import sg12 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/Ş.G. PRIVATE VILLA-ISTANBUL/12.jpg'
import sg13 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/Ş.G. PRIVATE VILLA-ISTANBUL/13.jpg'
import sg14 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/Ş.G. PRIVATE VILLA-ISTANBUL/14.jpg'

import sasali1 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/T.Ö. PRIVATE VILLA-SASALI İZMİR/1.jpg'
import sasali2 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/T.Ö. PRIVATE VILLA-SASALI İZMİR/2.jpg'
import sasali3 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/T.Ö. PRIVATE VILLA-SASALI İZMİR/3.jpg'
import sasali4 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/T.Ö. PRIVATE VILLA-SASALI İZMİR/4.jpg'
import sasali5 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/T.Ö. PRIVATE VILLA-SASALI İZMİR/5.jpg'
import sasali6 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/T.Ö. PRIVATE VILLA-SASALI İZMİR/6.jpg'
import sasali7 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/T.Ö. PRIVATE VILLA-SASALI İZMİR/7.jpg'
import sasali8 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/T.Ö. PRIVATE VILLA-SASALI İZMİR/8.jpg'
import sasali9 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/T.Ö. PRIVATE VILLA-SASALI İZMİR/9.jpg'

import vadiurla1 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/VADİ KEKLİKTEPE-URLA İZMİR/1.jpg'
import vadiurla2 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/VADİ KEKLİKTEPE-URLA İZMİR/2.jpg'
import vadiurla3 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/VADİ KEKLİKTEPE-URLA İZMİR/3.jpg'
import vadiurla4 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/VADİ KEKLİKTEPE-URLA İZMİR/4.jpg'
import vadiurla5 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/VADİ KEKLİKTEPE-URLA İZMİR/5.jpg'
import vadiurla6 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/VADİ KEKLİKTEPE-URLA İZMİR/6.jpg'
import vadiurla7 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/VADİ KEKLİKTEPE-URLA İZMİR/7.jpg'
import vadiurla8 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/VADİ KEKLİKTEPE-URLA İZMİR/8.jpg'
import vadiurla9 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/VADİ KEKLİKTEPE-URLA İZMİR/9.jpg'
import vadiurla10 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/VADİ KEKLİKTEPE-URLA İZMİR/10.jpg'
import vadiurla11 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/VADİ KEKLİKTEPE-URLA İZMİR/11.jpg'
import vadiurla12 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/VADİ KEKLİKTEPE-URLA İZMİR/12.jpg'
import vadiurla13 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/VADİ KEKLİKTEPE-URLA İZMİR/13.jpg'
import vadiurla14 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/VADİ KEKLİKTEPE-URLA İZMİR/14.jpg'
import vadiurlaytk1 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/VADİ KEKLİKTEPE-URLA İZMİR/YATAK ODA/1.jpg'
import vadiurlaytk2 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/VADİ KEKLİKTEPE-URLA İZMİR/YATAK ODA/2.jpg'
import vadiurlaytk3 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/VADİ KEKLİKTEPE-URLA İZMİR/YATAK ODA/3.jpg'
import vadiurlaytk4 from './src/assets/PROJECTS-GALLERY/1-PRIVATE-RESIDENTAL-PROJECTS(RESIDENTAL)/VADİ KEKLİKTEPE-URLA İZMİR/YATAK ODA/4.jpg'



import folkartincity1 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL APARTMENT- FOLKART INCITY/1.jpg'
import folkartincity2 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL APARTMENT- FOLKART INCITY/2.jpg'
import folkartincity3 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL APARTMENT- FOLKART INCITY/3.jpg'
import folkartincity4 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL APARTMENT- FOLKART INCITY/4.jpg'
import folkartincity5 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL APARTMENT- FOLKART INCITY/5.jpg'

import individualblg1 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL HOUSE, BULGARIA/1.jpg'
import individualblg2 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL HOUSE, BULGARIA/2.jpg'
import individualblg3 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL HOUSE, BULGARIA/3.jpg'
import individualblg4 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL HOUSE, BULGARIA/4.jpg'
import individualblg5 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL HOUSE, BULGARIA/5.jpg'
import individualblg6 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL HOUSE, BULGARIA/6.jpg'
import individualblg7 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL HOUSE, BULGARIA/7.jpg'
import individualblg8 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL HOUSE, BULGARIA/8.jpg'

import individualant1 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL HOUSE-ANTALYA/1.jpg'
import individualant2 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL HOUSE-ANTALYA/2.jpg'
import individualant3 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL HOUSE-ANTALYA/3.jpg'
import individualant4 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL HOUSE-ANTALYA/4.jpg'
import individualant5 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL HOUSE-ANTALYA/5.jpg'

import individualcsm1 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL VILLA-ÇEŞME İZMİR/1.jpg'
import individualcsm2 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL VILLA-ÇEŞME İZMİR/2.jpg'
import individualcsm3 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL VILLA-ÇEŞME İZMİR/3.jpg'
import individualcsm4 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL VILLA-ÇEŞME İZMİR/4.jpg'
import individualcsm5 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL VILLA-ÇEŞME İZMİR/5.jpg'
import individualcsm6 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL VILLA-ÇEŞME İZMİR/6.jpg'
import individualcsm7 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL VILLA-ÇEŞME İZMİR/7.jpg'

import individualmkn1 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL VILLA-MİKONOS STYLE/1.jpg'
import individualmkn2 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL VILLA-MİKONOS STYLE/2.jpg'
import individualmkn3 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL VILLA-MİKONOS STYLE/3.jpg'
import individualmkn4 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL VILLA-MİKONOS STYLE/4.jpg'
import individualmkn5 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL VILLA-MİKONOS STYLE/5.jpg'
import individualmkn6 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL VILLA-MİKONOS STYLE/6.jpg'
import individualmkn7 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/INDIVIDUAL VILLA-MİKONOS STYLE/7.jpg'

import individualflk1 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/LIVING ROOM-FOLKART VEGA İZMİR/1.jpg'
import individualflk2 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/LIVING ROOM-FOLKART VEGA İZMİR/2.jpg'
import individualflk3 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/LIVING ROOM-FOLKART VEGA İZMİR/3.jpg'
import individualflk4 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/LIVING ROOM-FOLKART VEGA İZMİR/4.jpg'
import individualflk5 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/LIVING ROOM-FOLKART VEGA İZMİR/5.jpg'
import individualflk6 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/LIVING ROOM-FOLKART VEGA İZMİR/6.jpg'
import individualflk7 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/LIVING ROOM-FOLKART VEGA İZMİR/7.jpg'
import individualflk8 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/LIVING ROOM-FOLKART VEGA İZMİR/8.jpg'

import meneskoy1 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA A BLOK-MENESKÖY İZMİR/1.jpg'
import meneskoy2 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA A BLOK-MENESKÖY İZMİR/2.jpg'
import meneskoy3 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA A BLOK-MENESKÖY İZMİR/3.jpg'
import meneskoy4 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA A BLOK-MENESKÖY İZMİR/4.jpg'
import meneskoy5 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA A BLOK-MENESKÖY İZMİR/5.jpg'
import meneskoy6 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA A BLOK-MENESKÖY İZMİR/6.jpg'
import meneskoy7 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA A BLOK-MENESKÖY İZMİR/7.jpg'
import meneskoy8 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA A BLOK-MENESKÖY İZMİR/8.jpg'
import meneskoy9 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA A BLOK-MENESKÖY İZMİR/9.jpg'
import meneskoy10 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA A BLOK-MENESKÖY İZMİR/10.jpg'
import meneskoy11 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA A BLOK-MENESKÖY İZMİR/11.jpg'
import meneskoy12 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA A BLOK-MENESKÖY İZMİR/12.jpg'
import meneskoy13 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA A BLOK-MENESKÖY İZMİR/13.jpg'
import meneskoy14 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA A BLOK-MENESKÖY İZMİR/14.jpg'
import meneskoy15 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA A BLOK-MENESKÖY İZMİR/15.jpg'
import meneskoy16 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA A BLOK-MENESKÖY İZMİR/16.jpg'




import meneskoyb1 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/1.jpg'
import meneskoyb2 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/2.jpg'
import meneskoyb3 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/3.jpg'
import meneskoyb4 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/4.jpg'
import meneskoyb5 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/5.jpg'
import meneskoyb6 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/6.jpg'
import meneskoyb7 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/7.jpg'
import meneskoyb8 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/8.jpg'
import meneskoyb9 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/9.jpg'
import meneskoyb10 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/10.jpg'
import meneskoyb11 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/11.jpg'
import meneskoyb12 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/12.jpg'
import meneskoyb13 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/13.jpg'
import meneskoyb14 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/14.jpg'
import meneskoyb15 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/15.jpg'
import meneskoyb16 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/16.jpg'
import meneskoyb17 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/17.jpg'
import meneskoyb18 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/18.jpg'
import meneskoyb19 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/19.jpg'
import meneskoyb20 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA B BLOK-MENESKÖY İZMİR/20.jpg'

import lebiderya1 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA-LEB-I DERYA BODRUM/1.jpg'
import lebiderya2 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA-LEB-I DERYA BODRUM/2.jpg'
import lebiderya3 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA-LEB-I DERYA BODRUM/3.jpg'
import lebiderya4 from './src/assets/PROJECTS-GALLERY/2-CONTEMPORARY-PROJECTS-(RESIDENTAL)/PRIVATE VILLA-LEB-I DERYA BODRUM/4.jpg'

import maintal1 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/ARKADASH DONER RESTAURANT-MAINTAL GERMANY/1.jpg'
import maintal2 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/ARKADASH DONER RESTAURANT-MAINTAL GERMANY/2.jpg'
import maintal3 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/ARKADASH DONER RESTAURANT-MAINTAL GERMANY/3.jpg'
import maintal4 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/ARKADASH DONER RESTAURANT-MAINTAL GERMANY/4.jpg'
import maintal5 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/ARKADASH DONER RESTAURANT-MAINTAL GERMANY/5.jpg'
import maintal6 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/ARKADASH DONER RESTAURANT-MAINTAL GERMANY/6.jpg'
import maintal7 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/ARKADASH DONER RESTAURANT-MAINTAL GERMANY/7.jpg'

import balikci1 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/BALIKÇI HASAN-ALSANCAK İZMİR/1.jpg'
import balikci2 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/BALIKÇI HASAN-ALSANCAK İZMİR/2.jpg'
import balikci3 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/BALIKÇI HASAN-ALSANCAK İZMİR/3.jpg'
import balikci4 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/BALIKÇI HASAN-ALSANCAK İZMİR/4.jpg'
import balikci5 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/BALIKÇI HASAN-ALSANCAK İZMİR/5.jpg'
import balikci6 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/BALIKÇI HASAN-ALSANCAK İZMİR/6.jpg'
import balikci7 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/BALIKÇI HASAN-ALSANCAK İZMİR/7.jpg'
import balikci8 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/BALIKÇI HASAN-ALSANCAK İZMİR/8.jpg'
import balikci9 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/BALIKÇI HASAN-ALSANCAK İZMİR/9.jpg'

import concept1 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/CONCEPT RESTAURANT- FRANCE/1.jpg'
import concept2 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/CONCEPT RESTAURANT- FRANCE/2.jpg'
import concept3 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/CONCEPT RESTAURANT- FRANCE/3.jpg'
import concept4 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/CONCEPT RESTAURANT- FRANCE/4.jpg'
import concept5 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/CONCEPT RESTAURANT- FRANCE/5.jpg'
import concept6 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/CONCEPT RESTAURANT- FRANCE/6.jpg'
import concept7 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/CONCEPT RESTAURANT- FRANCE/7.jpg'
import concept8 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/CONCEPT RESTAURANT- FRANCE/8.jpg'
import concept9 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/CONCEPT RESTAURANT- FRANCE/9.jpg'
import concept10 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/CONCEPT RESTAURANT- FRANCE/10.jpg'
import concept11 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/CONCEPT RESTAURANT- FRANCE/11.jpg'
import concept12 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/CONCEPT RESTAURANT- FRANCE/12.jpg'
import concept13 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/CONCEPT RESTAURANT- FRANCE/13.jpg'
import concept14 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/CONCEPT RESTAURANT- FRANCE/14.jpg'

import eruz1 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/ERUZ LOBBY-URLA/1.jpg'
import eruz2 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/ERUZ LOBBY-URLA/2.jpg'
import eruz3 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/ERUZ LOBBY-URLA/3.jpg'
import eruz4 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/ERUZ LOBBY-URLA/4.jpg'
import eruz5 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/ERUZ LOBBY-URLA/5.jpg'
import eruz6 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/ERUZ LOBBY-URLA/6.jpg'
import eruz7 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/ERUZ LOBBY-URLA/7.jpg'
import eruz8 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/ERUZ LOBBY-URLA/8.jpg'
import eruz9 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/ERUZ LOBBY-URLA/9.jpg'
import eruz10 from './src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/ERUZ LOBBY-URLA/10.jpg'

import mana1 from "./src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/MA'NA RESTAURANT-FRANKFURT GERMANY/1.jpg"
import mana2 from "./src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/MA'NA RESTAURANT-FRANKFURT GERMANY/2.jpg"
import mana3 from "./src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/MA'NA RESTAURANT-FRANKFURT GERMANY/3.jpg"
import mana4 from "./src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/MA'NA RESTAURANT-FRANKFURT GERMANY/4.jpg"
import mana5 from "./src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/MA'NA RESTAURANT-FRANKFURT GERMANY/5.jpg"
import mana6 from "./src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/MA'NA RESTAURANT-FRANKFURT GERMANY/6.jpg"
import mana7 from "./src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/MA'NA RESTAURANT-FRANKFURT GERMANY/7.jpg"
import mana8 from "./src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/MA'NA RESTAURANT-FRANKFURT GERMANY/8.jpg"
import mana9 from "./src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/MA'NA RESTAURANT-FRANKFURT GERMANY/9.jpg"
import mana10 from "./src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/MA'NA RESTAURANT-FRANKFURT GERMANY/10.jpg"
import mana11 from "./src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/MA'NA RESTAURANT-FRANKFURT GERMANY/11.jpg"
import mana12 from "./src/assets/PROJECTS-GALLERY/3-HOSPITALITY-(HOSPITALITY)/MA'NA RESTAURANT-FRANKFURT GERMANY/12.jpg"


import cuzdan1 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/CÜZDAN-ATAŞEHİR İSTANBUL/1.jpg'
import cuzdan2 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/CÜZDAN-ATAŞEHİR İSTANBUL/2.jpg'
import cuzdan3 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/CÜZDAN-ATAŞEHİR İSTANBUL/3.jpg'
import cuzdan4 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/CÜZDAN-ATAŞEHİR İSTANBUL/4.jpg'

import iron1 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/IRON AND STEEL FACTORY- ALİAĞA İZMİR/1.jpg'
import iron2 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/IRON AND STEEL FACTORY- ALİAĞA İZMİR/2.jpg'
import iron3 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/IRON AND STEEL FACTORY- ALİAĞA İZMİR/3.jpg'
import iron4 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/IRON AND STEEL FACTORY- ALİAĞA İZMİR/4.jpg'
import iron5 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/IRON AND STEEL FACTORY- ALİAĞA İZMİR/5.jpg'
import iron6 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/IRON AND STEEL FACTORY- ALİAĞA İZMİR/6.jpg'
import iron7 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/IRON AND STEEL FACTORY- ALİAĞA İZMİR/7.jpg'
import iron8 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/IRON AND STEEL FACTORY- ALİAĞA İZMİR/8.jpg'
import iron9 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/IRON AND STEEL FACTORY- ALİAĞA İZMİR/9.jpg'
import iron10 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/IRON AND STEEL FACTORY- ALİAĞA İZMİR/10.jpg'
import iron11 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/IRON AND STEEL FACTORY- ALİAĞA İZMİR/11.jpg'
import iron12 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/IRON AND STEEL FACTORY- ALİAĞA İZMİR/12.jpg'
import iron13 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/IRON AND STEEL FACTORY- ALİAĞA İZMİR/13.jpg'
import iron14 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/IRON AND STEEL FACTORY- ALİAĞA İZMİR/14.jpg'
import iron15 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/IRON AND STEEL FACTORY- ALİAĞA İZMİR/15.jpg'


import izka1 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/IZKA OFFICE-İZMİR/1.jpg'
import izka2 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/IZKA OFFICE-İZMİR/2.jpg'
import izka3 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/IZKA OFFICE-İZMİR/3.jpg'
import izka4 from './src/assets/PROJECTS-GALLERY/4-OFFICE-PROJECTS-(OFFICE)/IZKA OFFICE-İZMİR/4.jpg'

import aidios1 from './src/assets/PROJECTS-GALLERY/5-FURNITURE-PRODUCT-DESIGN-(FURNITURE-PRODUCT)/AIDIOS TABLE & CONSOLE/1.jpg'
import aidios2 from './src/assets/PROJECTS-GALLERY/5-FURNITURE-PRODUCT-DESIGN-(FURNITURE-PRODUCT)/AIDIOS TABLE & CONSOLE/2.jpg'
import aidios3 from './src/assets/PROJECTS-GALLERY/5-FURNITURE-PRODUCT-DESIGN-(FURNITURE-PRODUCT)/AIDIOS TABLE & CONSOLE/3.jpg'
import aidios4 from './src/assets/PROJECTS-GALLERY/5-FURNITURE-PRODUCT-DESIGN-(FURNITURE-PRODUCT)/AIDIOS TABLE & CONSOLE/4.jpg'
import aidios5 from './src/assets/PROJECTS-GALLERY/5-FURNITURE-PRODUCT-DESIGN-(FURNITURE-PRODUCT)/AIDIOS TABLE & CONSOLE/5.jpg'
import aidios6 from './src/assets/PROJECTS-GALLERY/5-FURNITURE-PRODUCT-DESIGN-(FURNITURE-PRODUCT)/AIDIOS TABLE & CONSOLE/6.jpg'

import blade1 from './src/assets/PROJECTS-GALLERY/5-FURNITURE-PRODUCT-DESIGN-(FURNITURE-PRODUCT)/BLADE CONSOLE/1.jpg'
import blade2 from './src/assets/PROJECTS-GALLERY/5-FURNITURE-PRODUCT-DESIGN-(FURNITURE-PRODUCT)/BLADE CONSOLE/2.jpg'

import clavis from './src/assets/PROJECTS-GALLERY/5-FURNITURE-PRODUCT-DESIGN-(FURNITURE-PRODUCT)/CLAVIS TV WALL/1.jpg'


import concepthotel1 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/CONCEPT HOTEL/1.jpg'
import concepthotel2 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/CONCEPT HOTEL/2.jpg'
import concepthotel3 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/CONCEPT HOTEL/3.jpg'
import concepthotel4 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/CONCEPT HOTEL/4.jpg'


import konseptev1 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/konsept ev/1.jpg'
import konseptev2 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/konsept ev/2.jpg'
import konseptev3 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/konsept ev/3.jpg'
import konseptev4 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/konsept ev/4.jpg'
import konseptev5 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/konsept ev/5.jpg'
import konseptev6 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/konsept ev/6.jpg'
import konseptev7 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/konsept ev/7.jpg'
import konseptev8 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/konsept ev/8.jpg'
import konseptev9 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/konsept ev/9.jpg'
import konseptev10 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/konsept ev/10.jpg'
import konseptev11 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/konsept ev/11.jpg'
import konseptev12 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/konsept ev/12.jpg'
import konseptev13 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/konsept ev/13.jpg'
import konseptev14 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/konsept ev/14.jpg'
import konseptev15 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/konsept ev/15.jpg'
import konseptev16 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/konsept ev/16.jpg'



import moodbard1 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/moodboard/1.jpg'
import moodbard2 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/moodboard/2.jpg'
import moodbard3 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/moodboard/3.jpg'
import moodbard4 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/moodboard/4.jpg'
import moodbard5 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/moodboard/5.jpg'
import moodbard6 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/moodboard/6.jpg'
import moodbard7 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/moodboard/7.jpg'
import moodbard8 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/moodboard/8.jpg'
import moodbard9 from './src/assets/PROJECTS-GALLERY/6-FFE-SERVICE-STYLING-(FFE-SERVICE)/moodboard/9.jpg'

import austin1 from './src/assets/PROJECTS-GALLERY/7 EXTERIOR & FACADE/CONTEMPORARY VILLA-AUSTIN/1.jpg'
import austin2 from './src/assets/PROJECTS-GALLERY/7 EXTERIOR & FACADE/CONTEMPORARY VILLA-AUSTIN/2.jpg'
import austin3 from './src/assets/PROJECTS-GALLERY/7 EXTERIOR & FACADE/CONTEMPORARY VILLA-AUSTIN/3.jpg'
import austin4 from './src/assets/PROJECTS-GALLERY/7 EXTERIOR & FACADE/CONTEMPORARY VILLA-AUSTIN/4.jpg'


import residentalcover from './src/assets/cover/residental.jpg'
import residentalcover2 from './src/assets/cover/residental2.jpg'
import contemporary from './src/assets/cover/contemporary.jpg'
import contemporary2 from './src/assets/cover/contemporary2.jpg'
import hospitality from './src/assets/cover/hospitality.jpg'
import hospitality2 from './src/assets/cover/hospitality2.jpg'
import office from './src/assets/cover/office.jpg'
import office2 from './src/assets/cover/office2.png'
import furniture from './src/assets/cover/furniture.jpg'
import furniture2 from './src/assets/cover/furniture2.png'
import ffe from './src/assets/cover/ffe.jpg'
import ffe2 from './src/assets/cover/ffe2.png'




import menderescover from './src/assets/PROJECTS-GALLERY/porjectcover/menderes.jpg'
import kartalcover from './src/assets/PROJECTS-GALLERY/porjectcover/kartal.jpg'
import mesacover from './src/assets/PROJECTS-GALLERY/porjectcover/mesa.jpg'
import sahilevlericover from './src/assets/PROJECTS-GALLERY/porjectcover/sahilevleri-izmir.jpg'
import sgistcover from './src/assets/PROJECTS-GALLERY/porjectcover/sgist.jpg'
import sasalicover from './src/assets/PROJECTS-GALLERY/porjectcover/sasali.jpg'
import vadiurlacover from './src/assets/PROJECTS-GALLERY/porjectcover/vadiurla.jpg'
import folkartincitycover from './src/assets/PROJECTS-GALLERY/porjectcover/folkartincity.jpg'
import individualblgcover from './src/assets/PROJECTS-GALLERY/porjectcover/individualblg.jpg'
import individualantcover from './src/assets/PROJECTS-GALLERY/porjectcover/individualant.jpg'
import individualcsmcover from './src/assets/PROJECTS-GALLERY/porjectcover/individualcsm.jpg'
import mikonoscover from './src/assets/PROJECTS-GALLERY/porjectcover/mikonos.jpg'
import folkartcover from './src/assets/PROJECTS-GALLERY/porjectcover/folkart.jpg'
import meneskoyslncover from './src/assets/PROJECTS-GALLERY/porjectcover/meneskoysln.jpg'
import meneskoyslnbcover from './src/assets/PROJECTS-GALLERY/porjectcover/meneskoyslnb.jpg'
import lebideryacover from './src/assets/PROJECTS-GALLERY/porjectcover/lebiderya.jpg'
import maintalcover from './src/assets/PROJECTS-GALLERY/porjectcover/maintal.jpg'
import balikcicover from './src/assets/PROJECTS-GALLERY/porjectcover/balikci.jpg'
import conceptcover from './src/assets/PROJECTS-GALLERY/porjectcover/concept.jpg'
import eruzcover from './src/assets/PROJECTS-GALLERY/porjectcover/eruz.jpg'
import manacover from './src/assets/PROJECTS-GALLERY/porjectcover/mana.jpg'
import cuzdancover from './src/assets/PROJECTS-GALLERY/porjectcover/cuzdan.jpg'
import ironcover from './src/assets/PROJECTS-GALLERY/porjectcover/iron.jpg'
import izkacover from './src/assets/PROJECTS-GALLERY/porjectcover/izka.jpg'
import aidioscover from './src/assets/PROJECTS-GALLERY/porjectcover/aidios.jpg'
import bladecover from './src/assets/PROJECTS-GALLERY/porjectcover/blade.jpg'
import claviscover from './src/assets/PROJECTS-GALLERY/porjectcover/clavis.jpg'
import conceptcover2 from './src/assets/PROJECTS-GALLERY/porjectcover/concepthotel.jpg'
import konseptcover from './src/assets/PROJECTS-GALLERY/porjectcover/konseptev.jpg'
import moodbardcover from './src/assets/PROJECTS-GALLERY/porjectcover/moodbard.jpg'
import austincover from './src/assets/PROJECTS-GALLERY/porjectcover/austin.png'




export const homePage = [
    {
        category: "Private Residental Projects",
        name: "Creating unique, luxury spaces",
        image: residentalcover,
        image2: residentalcover2,
        link: "/projects/residental"
    },
    {
        category: "Contemporary Projects",
        name: "Low-key and modern style",
        image: contemporary,
        image2: contemporary2,
        link: "/projects/residental"
    },
    {
        category: "Hospitality",
        name: "Elegant restaurants & lounges",
        image: hospitality,
        image2: hospitality2,
        link: "/projects/hospitality"
    },
    {
        category: "Office Projects",
        name: "High-end office interiors",
        image: office,
        image2: office2,
        link: "/projects/office"
    },
    {
        category: "Furniture & Product Design",
        name: "Distinctive custom-made productions",
        image: furniture,
        image2: furniture2,
        link: "/projects/furnitureproduct"
    },
    {
        category: "FF&E Service & Styling",
        name: "Decorating and styling your home",
        image: ffe,
        image2: ffe2,
        link: "/projects/ffe-services"
    },
]

export const menderes = [
    {
        img:menderes1
    },
    {
        img:menderes2
    },
    {
        img:menderes3
    },
    {
        img:menderes4
    },
    {
        img:menderes5
    },
    {
        img:menderes6
    },
    {
        img:menderes7
    },
    {
        img:menderes8
    },
    {
        img:menderes9
    },
    {
        img:menderes10
    },
    {
        img:menderes11
    },
    {
        img:menderes12
    },
    {
        img:menderes13
    },
    {
        img:menderes14
    },
    {
        img:menderes15
    },
    {
        img:menderes16
    },
    {
        img:menderes17
    },
    {
        img:menderes18
    },
    {
        img:menderes19
    },
    {
        img:menderes20
    },
    {
        img:menderes21
    },
    {
        img:menderes22
    },
]

export const kartal = [
    {
        img: kartal1
    },
    {
        img: kartal2
    },
    {
        img: kartal3
    },
    {
        img: kartal4
    },
]

export const mesa =[
    {
        img: mesa1
    },
    {
        img: mesa2
    },
    {
        img: mesa3
    },
    {
        img: mesa4
    },
    {
        img: mesa5
    },
    {
        img: mesa6
    },
    {
        img: mesa7
    },
    {
        img: mesa8
    },
    {
        img: mesa9
    },
    {
        img: mesa10
    },
    {
        img: mesa11
    },
    {
        img: mesa12
    },
]

export const shl = [
    {
        img: shlsalon1
    },
    {
        img: shlsalon2
    },
    {
        img: shlsalon3
    },
    {
        img: shlsalon4
    },
    {
        img: shlsalon5
    },
    {
        img: shlsalon6
    },
    {
        img: shlsalon7
    },
    {
        img: shlsalon8
    },
    {
        img: shlsalon9
    },
    {
        img: shlsalon10
    },
    {
        img: shlsalon11
    },
    {
        img: shlsalon12
    },
    {
        img: shlsalon13
    },
    {
        img: shlsalon14
    },
    {
        img: shlyatak1
    },
    {
        img: shlyatak2
    },
    {
        img: shlyatak3
    },
    {
        img: shlyatak4
    },
    {
        img: shlyatak5
    },
    {
        img: shlyatak6
    },
    {
        img: shlyatak7
    },
    {
        img: shlyatak8
    }
]

export const sg = [
    {
        img: sg1
    },
    {
        img: sg2
    },
    {
        img: sg3
    },
    {
        img: sg4
    },
    {
        img: sg5
    },
    {
        img: sg6
    },
    {
        img: sg7
    },
    {
        img: sg8
    },
    {
        img: sg9
    },
    {
        img: sg10
    },
    {
        img: sg11
    },
    {
        img: sg12
    },
    {
        img: sg13
    },
    {
        img: sg14
    }
]

export const sasali = [
    {
        img: sasali1
    },
    {
        img: sasali2
    },
    {
        img: sasali3
    },
    {
        img: sasali4
    },
    {
        img: sasali5
    },
    {
        img: sasali6
    },
    {
        img: sasali7
    },
    {
        img: sasali8
    },
    {
        img: sasali9
    }
]

export const vadi = [
    {
        img: vadiurla1
    },
    {
        img: vadiurla2
    },
    {
        img: vadiurla3
    },
    {
        img: vadiurla4
    },
    {
        img: vadiurla5
    },
    {
        img: vadiurla6
    },
    {
        img: vadiurla7
    },
    {
        img: vadiurla8
    },
    {
        img: vadiurla9
    },
    {
        img: vadiurla10
    },
    {
        img: vadiurla11
    },
    {
        img: vadiurla12
    },
    {
        img: vadiurla13
    },
    {
        img: vadiurla14
    },
    {
        img: vadiurlaytk1
    },
    {
        img: vadiurlaytk2
    },
    {
        img: vadiurlaytk3
    },
    {
        img: vadiurlaytk4
    },
]

export const folkartincity = [
    {
        img: folkartincity1
    },
    {
        img: folkartincity2
    },
    {
        img: folkartincity3
    },
    {
        img: folkartincity4
    },
    {
        img: folkartincity5
    }
]

export const bulgaria = [
    {
        img: individualblg1
    },
    {
        img: individualblg2
    },
    {
        img: individualblg3
    },
    {
        img: individualblg4
    },
    {
        img: individualblg5
    },
    {
        img: individualblg6
    },
    {
        img: individualblg7
    },
    {
        img: individualblg8
    },
]

export const antalya = [
    {
        img: individualant1
    },
    {
        img: individualant2
    },
    {
        img: individualant3
    },
    {
        img: individualant4
    },
    {
        img: individualant5
    }
]

export const cesme = [
    {
        img: individualcsm1
    },
    {
        img: individualcsm2
    },
    {
        img: individualcsm3
    },
    {
        img: individualcsm4
    },
    {
        img: individualcsm5
    },
    {
        img: individualcsm6
    },
    {
        img: individualcsm7
    }
]

export const mkn = [
    {
        img:individualmkn1
    },
    {
        img:individualmkn2
    },
    {
        img:individualmkn3
    },
    {
        img:individualmkn4
    },
    {
        img:individualmkn5
    },
    {
        img:individualmkn6
    },
    {
        img:individualmkn7
    }
]

export const flkvega = [
    {
        img: individualflk1
    },
    {
        img: individualflk2
    },
    {
        img: individualflk3
    },
    {
        img: individualflk4
    },
    {
        img: individualflk5
    },
    {
        img: individualflk6
    },
    {
        img: individualflk7
    },
    {
        img: individualflk8
    }
]

export const meneskoy = [
    {
        img: meneskoy1
    },
    {
        img: meneskoy2
    },
    {
        img: meneskoy3
    },
    {
        img: meneskoy4
    },
    {
        img: meneskoy5
    },
    {
        img: meneskoy6
    },
    {
        img: meneskoy7
    },
    {
        img: meneskoy8
    },
    {
        img: meneskoy9
    },
    {
        img: meneskoy10
    },
    {
        img: meneskoy11
    },
    {
        img: meneskoy12
    },
    {
        img: meneskoy13
    },
    {
        img: meneskoy14
    },
    {
        img: meneskoy15
    },
    {
        img: meneskoy16
    },
]

export const meneskoyb = [
    {
        img: meneskoyb1
    },
    {
        img: meneskoyb2
    },
    {
        img: meneskoyb3
    },
    {
        img: meneskoyb4
    },
    {
        img: meneskoyb5
    },
    {
        img: meneskoyb6
    },
    {
        img: meneskoyb7
    },
    {
        img: meneskoyb8
    },
    {
        img: meneskoyb9
    },
    {
        img: meneskoyb10
    },
    {
        img: meneskoyb11
    },
    {
        img: meneskoyb12
    },
    {
        img: meneskoyb13
    },
    {
        img: meneskoyb14
    },
    {
        img: meneskoyb15
    },
    {
        img: meneskoyb16
    },
    {
        img: meneskoyb17
    },
    {
        img: meneskoyb18
    },
    {
        img: meneskoyb19
    },
    {
        img: meneskoyb20
    },
]

export const lebi = [
    {
        img: lebiderya1
    },
    {
        img: lebiderya2
    },
    {
        img: lebiderya3
    },
    {
        img: lebiderya4
    },
]

export const maintal = [
    {
        img: maintal1
    },
    {
        img: maintal2
    },
    {
        img: maintal3
    },
    {
        img: maintal4
    },
    {
        img: maintal5
    },
    {
        img: maintal6
    },
    {
        img: maintal7
    }
]

export const balikci = [
    {
        img: balikci1
    },
    {
        img: balikci2
    },
    {
        img: balikci3
    },
    {
        img: balikci4
    },
    {
        img: balikci5
    },
    {
        img: balikci6
    },
    {
        img: balikci7
    },
    {
        img: balikci8
    },
    {
        img: balikci9
    }
]

export const concept = [
    {
        img: concept1
    },
    {
        img: concept2
    },
    {
        img: concept3
    },
    {
        img: concept4
    },
    {
        img: concept5
    },
    {
        img: concept6
    },
    {
        img: concept7
    },
    {
        img: concept8
    },
    {
        img: concept9
    },
    {
        img: concept10
    },
    {
        img: concept11
    },
    {
        img: concept12
    },
    {
        img: concept13
    },
    {
        img: concept14
    },
]

export const eruz = [
    {
        img: eruz1
    },
    {
        img: eruz2
    },
    {
        img: eruz3
    },
    {
        img: eruz4
    },
    {
        img: eruz5
    },
    {
        img: eruz6
    },
    {
        img: eruz7
    },
    {
        img: eruz8
    },
    {
        img: eruz9
    },
    {
        img: eruz10
    }
]

export const mana = [
    {
        img: mana1
    },
    {
        img: mana2
    },
    {
        img: mana3
    },
    {
        img: mana4
    },
    {
        img: mana5
    },
    {
        img: mana6
    },
    {
        img: mana7
    },
    {
        img: mana8
    },
    {
        img: mana9
    },
    {
        img: mana10
    },
    {
        img: mana11
    },
    {
        img: mana12
    }
]

export const cuzdan = [
    {
        img: cuzdan1
    },
    {
        img: cuzdan2
    },
    {
        img: cuzdan3
    },
    {
        img: cuzdan4
    }
]

export const iron = [
    {
        img: iron1
    },
    {
        img: iron2
    },
    {
        img: iron3
    },
    {
        img: iron4
    },
    {
        img: iron5
    },
    {
        img: iron6
    },
    {
        img: iron7
    },
    {
        img: iron8
    },
    {
        img: iron9
    },
    {
        img: iron10
    },
    {
        img: iron11
    },
    {
        img: iron12
    },
    {
        img: iron13
    },
    {
        img: iron14
    },
    {
        img: iron15
    },
]

export const izka = [
    {
        img: izka1
    },
    {
        img: izka2
    },
    {
        img: izka3
    },
    {
        img: izka4
    },
]

export const aidios = [
    {
        img: aidios1
    },
    {
        img: aidios2
    },
    {
        img: aidios3
    },
    {
        img: aidios4
    },
    {
        img: aidios5
    },
    {
        img: aidios6
    }
]

export const blade = [
    {
        img: blade1
    },
    {
        img: blade2
    }
]

export const clavisArr = [
    {
        img: clavis
    }
]

export const concepthotel = [
    {
        img: concepthotel1
    },
    {
        img: concepthotel2
    },
    {
        img: concepthotel3
    },
    {
        img: concepthotel4
    },
]

export const konseptev = [
    {
        img: konseptev1
    },
    {
        img: konseptev2
    },
    {
        img: konseptev3
    },
    {
        img: konseptev4
    },
    {
        img: konseptev5
    },
    {
        img: konseptev6
    },
    {
        img: konseptev7
    },
    {
        img: konseptev8
    },
    {
        img: konseptev9
    },
    {
        img: konseptev10
    },
    {
        img: konseptev11
    },
    {
        img: konseptev12
    },
    {
        img: konseptev13
    },
    {
        img: konseptev14
    },
    {
        img: konseptev15
    },
    {
        img: konseptev16
    },
]

export const moodbard = [
    {
        img: moodbard1
    },
    {
        img: moodbard2
    },
    {
        img: moodbard3
    },
    {
        img: moodbard4
    },
    {
        img: moodbard5
    },
    {
        img: moodbard6
    },
    {
        img: moodbard7
    },
    {
        img: moodbard8
    },
    {
        img: moodbard9
    }
]

export const austin = [
    {
        img: austin1
    },
    {
        img: austin2
    },
    {
        img: austin3
    },
    {
        img: austin4
    },
]








export const allProjects = [
    {
        id:1,
        category: "Residental",
        name:"HD Private House - Menderes",
        image: menderescover,
        link: "hd-private-house-menderes"
    },
    {
        id:2,
        category: "Residental",
        name:"Luxury Bedroom - Kartal Yuvası Bodrum",
        image: kartalcover,
        link: "luxury-bedroom-kartal-yuvasi-bodrum"
    },
    {
        id:3,
        category: "Residental",
        name:"Mesa Bodrum Demirbükü",
        image: mesacover,
        link: "mesa-bodrum-demirbuku"
    },
    {
        id:4,
        category: "Residental",
        name:"Private Villa - Sahilevleri İzmir",
        image: sahilevlericover,
        link: "private-villa-sahilevleri-izmir"
    },
    {
        id:5,
        category: "Residental",
        name:"Ş.G Private Villa - İstanbul",
        image: sgistcover,
        link: "sg-private-villa-istanbul"
    },
    {
        id:6,
        category: "Residental",
        name:"T.Ö Private Villa - Sasali İzmir",
        image: sasalicover,
        link: "to-private-villa-sasali-izmir"
    },
    {
        id:7,
        category: "Residental",
        name:"Vadi Kekliktepe - Urla İzmir",
        image: vadiurlacover,
        link: "vadi-kekliktepe-urla-izmir"
    },
    {
        id:8,
        category: "Residental",
        name:"Individual Apartment - Folkart Incity",
        image: folkartincitycover,
        link: "individual-apartment-folkart-incity"
    },
    {
        id:9,
        category: "Residental",
        name:"Individual House - Bulgaria",
        image: individualblgcover,
        link: "individual-house-bulgaria"
    },
    {
        id:10,
        category: "Residental",
        name:"Individual House - Antalya",
        image: individualantcover,
        link: "individual-house-antalya"
    },
    {
        id:11,
        category: "Residental",
        name:"Individual House - Çeşme İzmir",
        image: individualcsmcover,
        link: "individual-house-cesme-izmir"
    },
    {
        id:12,
        category: "Residental",
        name:"Individual Villa - Mikonos Style",
        image: mikonoscover,
        link: "individual-villa-mikonos-style"
    },
    {
        id:13,
        category: "Residental",
        name:"Living Room - Folkart Vega İzmir ",
        image: folkartcover,
        link: "living-room-folkart-vega-izmir"
    },
    {
        id:14,
        category: "Residental",
        name:"Private Villa A Blok - Menesköy İzmir",
        image: meneskoyslncover,
        link: "private-villa-a-blok-meneskoy-izmir"
    },
    {
        id:15,
        category: "Residental",
        name:"Private Villa B Blok - Menesköy İzmir",
        image: meneskoyslnbcover,
        link: "private-villa-b-blok-meneskoy-izmir"
    },
    {
        id:16,
        category: "Residental",
        name:"Private Villa - Leb-i Derya Bodrum",
        image: lebideryacover,
        link: "private-villa-leb-i-derya-bodrum"
    },
    {
        id:17,
        category: "Hospitality",
        name:"Arkadash Doner Restaurant - Maintal Germany",
        image: maintalcover,
        category: "Hospitality",
        link: "arkadash-doner-restaurant-maintal-germany"
    },
    {
        id:18,
        category: "Hospitality",
        name:"Balıkçı Hasan - Alsancak İzmir",
        image: balikcicover,
        category: "Hospitality",
        link: "balikci-hasan-alsancak-izmir"
    },
    {
        id:19,
        category: "Hospitality",
        name:"Concept Restaurant - France",
        image: conceptcover,
        category: "Hospitality",
        link: "concept-restaurant-france"
    },
    {
        id:20,
        category: "Hospitality",
        name:"Eruz Lobby - Urla",
        image: eruzcover,
        category: "Hospitality",
        link: "eruz-lobby-urla"
    },
    {
        id:21,
        category: "Hospitality",
        name:"Mana Restaurant - Frankfurt Germany",
        image: manacover,
        category: "Hospitality",
        link: "mana-restaurant-frankfurt-germany"
    },
    {
        id: 22,
        category: "Office",
        name: "Cüzdan - Ataşehir İstanbul",
        image: cuzdancover,
        link: "cuzdan-atasehir-istanbul"
    },
    {
        id: 23,
        category: "Office",
        name: "Iron and Steel Factory - Aliağa İzmir",
        image: ironcover,
        link: "iron-and-steel-factory-aliaga-izmir"
    },
    {
        id: 24,
        category: "Office",
        name: "Izka Office - İzmir",
        image: izkacover,
        link: "izka-office-izmir"
    },
    {
        id: 25,
        category: "Furniture & Product Design",
        name: "Aidios Table & Console",
        image: aidioscover,
        link: "aidios-table-console"
    },
    {
        id: 26,
        category: "Furniture & Product Design",
        name: "Blade Console",
        image: bladecover,
        link: "blade-console"
    },
    {
        id: 27,
        category: "Furniture & Product Design",
        name: "Clavis TV Wall",
        image: claviscover,
        link: "clavis-tv-wall"
    },
    {
        id: 28,
        category: "FF&E Services",
        name: "Concept Hotel",
        image: conceptcover2,
        link: "concept-hotel"
    },
    {
        id: 29,
        category: "FF&E Services",
        name: "Konsept Ev",
        image: konseptcover,
        link:"konsept-ev"
    },
    {
        id: 30,
        category: "FF&E Services",
        name: "Moodbard",
        image: moodbardcover,
        link:"moodbard"
    },
    {
        id: 31,
        category: "Exterior & Facade",
        name: "Contemporary Villa - Austin",
        image: austincover,
        link: "contemporary-villa-austin"
    },
]

export const residental = [
    {
        id:1,
        category: "Residental",
        name:"HD Private House - Menderes",
        image: menderescover,
        link: "hd-private-house-menderes"
    },
    {
        id:2,
        category: "Residental",
        name:"Luxury Bedroom - Kartal Yuvası Bodrum",
        image: kartalcover,
        link: "luxury-bedroom-kartal-yuvasi-bodrum"
    },
    {
        id:3,
        category: "Residental",
        name:"Mesa Bodrum Demirbükü",
        image: mesacover,
        link: "mesa-bodrum-demirbuku"
    },
    {
        id:4,
        category: "Residental",
        name:"Private Villa - Sahilevleri İzmir",
        image: sahilevlericover,
        link: "private-villa-sahilevleri-izmir"
    },
    {
        id:5,
        category: "Residental",
        name:"Ş.G Private Villa - İstanbul",
        image: sgistcover,
        link: "sg-private-villa-istanbul"
    },
    {
        id:6,
        category: "Residental",
        name:"T.Ö Private Villa - Sasali İzmir",
        image: sasalicover,
        link: "to-private-villa-sasali-izmir"
    },
    {
        id:7,
        category: "Residental",
        name:"Vadi Kekliktepe - Urla İzmir",
        image: vadiurlacover,
        link: "vadi-kekliktepe-urla-izmir"
    },
    {
        id:8,
        category: "Residental",
        name:"Individual Apartment - Folkart Incity",
        image: folkartincitycover,
        link: "individual-apartment-folkart-incity"
    },
    {
        id:9,
        category: "Residental",
        name:"Individual House - Bulgaria",
        image: individualblgcover,
        link: "individual-house-bulgaria"
    },
    {
        id:10,
        category: "Residental",
        name:"Individual House - Antalya",
        image: individualantcover,
        link: "individual-house-antalya"
    },
    {
        id:11,
        category: "Residental",
        name:"Individual House - Çeşme İzmir",
        image: individualcsmcover,
        link: "individual-house-cesme-izmir"
    },
    {
        id:12,
        category: "Residental",
        name:"Individual Villa - Mikonos Style",
        image: mikonoscover,
        link: "individual-villa-mikonos-style"
    },
    {
        id:13,
        category: "Residental",
        name:"Living Room - Folkart Vega İzmir ",
        image: folkartcover,
        link: "living-room-folkart-vega-izmir"
    },
    {
        id:14,
        category: "Residental",
        name:"Private Villa A Blok - Menesköy İzmir",
        image: meneskoyslncover,
        link: "private-villa-a-blok-meneskoy-izmir"
    },
    {
        id:15,
        category: "Residental",
        name:"Private Villa B Blok - Menesköy İzmir",
        image: meneskoyslnbcover,
        link: "private-villa-b-blok-meneskoy-izmir"
    },
    {
        id:16,
        category: "Residental",
        name:"Private Villa - Leb-i Derya Bodrum",
        image: lebideryacover,
        link: "private-villa-leb-i-derya-bodrum"
    }
]

export const hospitalityArr = [
    {
        id:1,
        category: "Hospitality",
        name:"Arkadash Doner Restaurant - Maintal Germany",
        image: maintalcover,
        category: "Hospitality",
        link: "arkadash-doner-restaurant-maintal-germany"
    },
    {
        id:2,
        category: "Hospitality",
        name:"Balıkçı Hasan - Alsancak İzmir",
        image: balikcicover,
        category: "Hospitality",
        link: "balikci-hasan-alsancak-izmir"
    },
    {
        id:3,
        category: "Hospitality",
        name:"Concept Restaurant - France",
        image: conceptcover,
        category: "Hospitality",
        link: "concept-restaurant-france"
    },
    {
        id:4,
        category: "Hospitality",
        name:"Eruz Lobby - Urla",
        image: eruzcover,
        category: "Hospitality",
        link: "eruz-lobby-urla"
    },
    {
        id:5,
        category: "Hospitality",
        name:"Mana Restaurant - Frankfurt Germany",
        image: manacover,
        category: "Hospitality",
        link: "mana-restaurant-frankfurt-germany"
    },
]

export const officeArr = [
    {
        id: 1,
        category: "Office",
        name: "Cüzdan - Ataşehir İstanbul",
        image: cuzdancover,
        link: "cuzdan-atasehir-istanbul"
    },
    {
        id: 2,
        category: "Office",
        name: "Iron and Steel Factory - Aliağa İzmir",
        image: ironcover,
        link: "iron-and-steel-factory-aliaga-izmir"
    },
    {
        id: 3,
        category: "Office",
        name: "Izka Office - İzmir",
        image: izkacover,
        link: "izka-office-izmir"
    },
]

export const furnitureArr = [
    {
        id: 1,
        category: "Furniture & Product Design",
        name: "Aidios Table & Console",
        image: aidioscover,
        link: "aidios-table-console"
    },
    {
        id: 2,
        category: "Furniture & Product Design",
        name: "Blade Console",
        image: bladecover,
        link: "blade-console"
    },
    {
        id: 3,
        category: "Furniture & Product Design",
        name: "Clavis TV Wall",
        image: claviscover,
        link: "clavis-tv-wall"
    },
]

export const ffeArr = [
    {
        id: 1,
        category: "FF&E Services",
        name: "Concept Hotel",
        image: conceptcover2,
        link: "concept-hotel"
    },
    {
        id: 2,
        category: "FF&E Services",
        name: "Konsept Ev",
        image: konseptcover,
        link:"konsept-ev"
    },
    {
        id: 3,
        category: "FF&E Services",
        name: "Moodbard",
        image: moodbardcover,
        link:"moodbard"
    },
]

export const exterior = [
    {
        id: 1,
        category: "Exterior & Facade",
        name: "Contemporary Villa - Austin",
        image: austincover,
        link: "contemporary-villa-austin"
    },
]